### ISSUE TITLE
能设置支持typescript嘛

### ISSUE THREAD

**Issue by LiuWeiMr** [taccisum/swagger-doc-snippets#1]

**Comment by taccisum** [comment]
已经支持了
https://github.com/taccisum/swagger-doc-snippets/releases/tag/v0.1.0

**Comment by LiuWeiMr** [comment]
好的，我看下




| |
刘伟
邮箱：nmgliuw@163.com
|

签名由 网易邮箱大师 定制

在2019年07月01日 10:26，taccisum 写道：

已经支持了
https://github.com/taccisum/swagger-doc-snippets/releases/tag/v0.1.0
